name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test Just options

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: extractions/setup-just@v1
        with:
          just-version: 1.1.3
        env:
          # this is not required but add it if you get any rate limiting issues
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: just check
      - run: just --list
      - run: just --summary
